apiVersion: apps/v1
kind: Deployment
metadata:
 name: microservice-deployment
 labels:
  app: microservices-pod
spec:
 replicas: 1
 selector:
  matchLabels:
   app: microservices-pod
 template:
  metadata:
   labels:
    app: microservices-pod
  spec:
   containers:
    - name: microservices-springboot-container
      image: lincolnppires/microservices-springboot
      ports:
       - containerPort: 8081 
 