apiVersion: v1
kind: Pod
metadata:
 name: backend-pod
 labels:
  app: backend-pod
spec:
 containers:
  - name: backend-container
    image: lincolnppires/backend-servlet
    ports:
     - containerPort: 8080 
 